name: Pull codes

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4

    steps:
    - name: Install Dependencies
      run: |
        pwd
        . /home/ho/venvs/shorty.sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pull codes
      run: |
        cd /home/ho/projects/shorty
        git pull
    - name: Run Tests
      run: |
        cd /home/ho/projects/shorty
        python manage.py test
